blog/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign_up' }

  resources :post_attachments do
    resources :products
  end

  resources :posts

  resources :documents

  devise_for :users, path_names: { log_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'site/contact'
  get 'site/about'
  get 'site/index'

  root 'site#index'

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, post_attachments_attributes: [:id, :post_id, :avatar, :productname, :price])
    end
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/posts/_form.html.erb
<div class="form">
  <%= form_for(@post, :html => { :multipart => true }) do |f| %>
      <div class="field">
        <%= f.label :Name ,class: 'white'%><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <%= f.fields_for :post_attachments do |p| %>
          <div class="field">
            <%= p.label :avatar, class: 'white' %><br>
            <%= p.file_field :avatar,:multiple => true, name: "post_attachments[avatar][]",class:'white' %>
          </div>
      <% end %>

      <div class="actions">
        <%= f.submit class:'btn btn-success'%>
      </div>
  <% end %>
  <%= link_to 'Show', @post %>
  <%= link_to 'Back', posts_path %>
</div>

blog/app/views/posts/edit.html.erb
<div class="container contents">
  <h1 class="white text-center title">Editing Post</h1>
  <hr/>
  <div class="user-icon"><span class="fa fa-5x fa-pencil z-index white"></span></div>
  <div class="user-icon-backdrop"></div>
  <%= render 'form' %>

  <br/>
  <br/>
  <br/>
</div>

blog/app/views/posts/index.html.erb
<div class="container contents">
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want delete ' +  post.title + '?' } %></td>
        </tr>


    <% end %>

    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>
</div>

blog/app/views/posts/new.html.erb
<div class="container contents">
  <h1 class="white text-center">New Post</h1>
  <hr/>
  <div class="user-icon"></div>
  <div class="user-icon-backdrop"></div>
  <%= render 'form' %>

  <br/>
  <br/>
</div>

blog/app/views/posts/show.html.erb
<div class="container contents">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <% @post_attachments.each do |p| %>
      <%= image_tag p.avatar_url %>
      <%= link_to "Open Menu", post_attachments_path(p) %>
  <% end %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>