blog/config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign_up' }

  resources :post_attachments do
    resources :products
  end

  resources :posts

  resources :documents

  devise_for :users, path_names: { log_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'site/contact'
  get 'site/about'
  get 'site/index'

  root 'site#index'

end

blog/app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  has_many :products
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
end

blog/app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :check_if_admin, :only => [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  def check_if_admin
    authenticate_or_request_with_http_basic("Products Realm") do |username, password|
      username == "admin" and password == "sTr0NG_p4$swOrD"
    end
  end

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  def admin

  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
    @post_attachment = PostAttachment.find(params[:id])
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post_attachment
    @post_attachment = PostAttachment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_attachment_params
    params.require(:post_attachment).permit(:post_id, :avatar, :productname, :price)
  end
end

blog/app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

blog/app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= image_tag @post_attachment.avatar %>
    <%= form_for(@post_attachment) do |f| %>
        <div class="field">
          <%= f.label :avatar %><br>
          <%= f.file_field :avatar %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% end %>

blog/app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

blog/app/views/post_attachments/index.html.erb
<div class="page-wrap">
  <div class="container-pixed">
    <div class="container contents">
      <h3 class="text-center white title">Daily Breads</h3>
      <hr/>
      <div class="row">
        <% @post_attachments.each do |post_attachment| %>
            <div class="col-md-3">
              <%=  link_to (image_tag post_attachment.avatar, :class => "avatar img-thumbnail image item-menu"), post_attachment %>
              <%= render post_attachment.products %>
              <br/><br/>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

blog/app/views/post_attachments/menu.html.erb
<h1>Menus</h1>

<table>

  <tbody>

  <% @post_attachments.each do |post_attachment| %>

      <tr>
        <td><div class="img-responsive img-thumbnail"><%= image_tag post_attachment.avatar %></div></td>
        <td><%= post_attachment.avatar %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

blog/app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

blog/app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @post_attachment.avatar, :class => "avatar img-thumbnail" %>
<br/><br/>

<%= render @post_attachment.products %>

    <%= render 'products/form' %>


    <%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
    <%= link_to 'Delete', @post_attachment, method: :delete, data: { confirm: 'Are you sure you want to delete ' + @post_attachment.avatar.to_s + '?' } %> |

    <%= link_to 'New Product', new_post_path %>
<%= link_to 'Back', post_attachments_path %>